Desktop/new_directory/travel_diary/config/routes.rb
Rails.application.routes.draw do

  resources :reviews
  resources :cities
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Desktop/new_directory/travel_diary/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Desktop/new_directory/travel_diary/app/models/city.rb
class City < ApplicationRecord
  has_many :reviews

  has_attached_file :picture, styles: { medium:  "300x300#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

Desktop/new_directory/travel_diary/app/models/review.rb
class Review < ApplicationRecord
  belongs_to :city
  has_attached_file :picture, styles: { medium:  "300x300#", thumb: "100x100#" }, default_url: "/images/:style/missing.png"

  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

end

Desktop/new_directory/travel_diary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Desktop/new_directory/travel_diary/app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @reviews = @city.reviews
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.fetch(:city, {}) .permit(:name, :picture)

    end
end

Desktop/new_directory/travel_diary/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.fetch(:review, {}).permit(:title, :body, :city_id, :picture)
    end
end

Desktop/new_directory/travel_diary/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @cities = City.all
  end
end

Desktop/new_directory/travel_diary/app/helpers/application_helper.rb
module ApplicationHelper
end

Desktop/new_directory/travel_diary/app/helpers/cities_helper.rb
module CitiesHelper
end

Desktop/new_directory/travel_diary/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Desktop/new_directory/travel_diary/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

Desktop/new_directory/travel_diary/app/views/cities/_form.html.erb
<%= form_for(city) do |f| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>

      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-fields">
  <p>Name: <%= f.text_field :name %></p>
  <p>Picture: <%= f.file_field :picture%></p>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Desktop/new_directory/travel_diary/app/views/cities/edit.html.erb
<h1 class="page-title">Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

Desktop/new_directory/travel_diary/app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.name %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

Desktop/new_directory/travel_diary/app/views/cities/new.html.erb
<h1 class="page-title">New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

Desktop/new_directory/travel_diary/app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-title"><%= @city. name %></h1>

<div class="content-grid">
  <% @reviews.each do |review| %>
    <%= link_to review_path(review) do %>
      <div class="content-block">
        <div class="content-image"><%= image_tag review.picture.url (:medium) %></div>
        <div class="content-title"><%= review.title %></div>
      </div>
    <% end %>
  <% end %>
</div>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

Desktop/new_directory/travel_diary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelDiary</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="header">Travel Diary</h1>
    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

Desktop/new_directory/travel_diary/app/views/reviews/_form.html.erb
<%= form_for(review) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-fields">
  <p>City: <%= f.collection_select :city_id, City.all, :id, :name %></p>
  <p>Title: <%= f.text_field :title %></p>
  <p>Picture: <%= f.file_field :picture %></p>
  <p><%= f.text_area :body, size: "70x20" %></p>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Desktop/new_directory/travel_diary/app/views/reviews/edit.html.erb
<h1 class="page-title">Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

Desktop/new_directory/travel_diary/app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

Desktop/new_directory/travel_diary/app/views/reviews/new.html.erb
<h1 class="page-title">New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

Desktop/new_directory/travel_diary/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="page-title"><%= @review.title %></h1>
<div class="page-image"><%= image_tag @review.picture.url (:medium) %></div>

<div class="review-body"><%= @review.body %></div>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

Desktop/new_directory/travel_diary/app/views/static_pages/home.html.erb
<div class="content-grid">
  <% @cities.each do |city| %>
  <%= link_to city_path(city) do %>
  <div class="content-block">
    <div class="content-image"><%= image_tag city.picture.url (:medium) %></div>
    <div class="content-title"><%= city.name %></div>
  </div>
  <% end %>
  <% end %>
</div>